-- we can read Lua syntax here!
return {
    ["text_lang"] = "en-US",
    ["font_base_weight"] = 0,
    ["font_hinting"] = 2,
    ["font_kerning"] = 3,
    ["render_mode"] = 0,
    ["embedded_css"] = true,
    ["embedded_fonts"] = true,
    ["smooth_scaling"] = false,
    ["nightmode_images"] = true,
    ["percent_finished"] = 0.016181229773463,
    ["header_font_face"] = "Noto Sans",
    ["copt_font_size"] = 22,
    ["copt_font_base_weight"] = 0,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_word_spacing"] = {
        [2] = 75,
        [1] = 95,
    },
    ["copt_word_expansion"] = 0,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_line_spacing"] = 100,
    ["copt_font_gamma"] = 15,
    ["gamma"] = 1,
    ["highlight_drawer"] = "lighten",
    ["text_lang_embedded_langs"] = true,
    ["copt_rotation_mode"] = 0,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_force_algorithmic"] = false,
    ["floating_punctuation"] = 0,
    ["show_overlap_enable"] = false,
    ["line_space_percent"] = 100,
    ["hide_nonlinear_flows"] = false,
    ["bookmarks"] = {
        [2] = {
            ["chapter"] = "",
            ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().806",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().806",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().839",
            ["text"] = "more info from laptop",
            ["highlighted"] = true,
            ["notes"] = "we acknowledge our greatest debt.",
            ["datetime"] = "2023-01-24 04:36:02",
        },
        [5] = {
            ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().0",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().0",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().108",
            ["datetime"] = "2023-01-23 06:19:09",
            ["chapter"] = "",
            ["notes"] = "We are grateful to friends and colleagues who read the manuscript and contributed suggestions and criticism.",
            ["highlighted"] = true,
        },
        [3] = {
            ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().595",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().595",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().608",
            ["datetime"] = "2023-01-23 06:20:41",
            ["chapter"] = "",
            ["notes"] = "Nancy Goddard",
            ["highlighted"] = true,
        },
        [1] = {
            ["chapter"] = "",
            ["page"] = "/body/DocFragment[5]/body/div/p[4]/text()[1].4",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[4]/text()[1].4",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[4]/span[2]/text().6",
            ["text"] = "more testing - note added on laptop",
            ["highlighted"] = true,
            ["notes"] = "ALLACE GODDARD",
            ["datetime"] = "2023-01-24 03:45:58",
        },
        [4] = {
            ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().362",
            ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().362",
            ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().424",
            ["datetime"] = "2023-01-23 06:30:18",
            ["chapter"] = "",
            ["notes"] = ", who saw the benefit of reissuing this book; to Theodore Cohn",
            ["highlighted"] = true,
        },
    },
    ["bookmarks_sorted"] = true,
    ["bookmarks_sorted_20220106"] = true,
    ["cre_dom_version"] = 20210904,
    ["highlight"] = {
        [5] = {
            [2] = {
                ["text"] = "Nancy Goddard",
                ["drawer"] = "lighten",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().608",
                ["chapter"] = "",
                ["datetime"] = "2023-01-23 06:20:41",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().595",
            },
            [5] = {
                ["text"] = "we acknowledge our greatest debt.",
                ["drawer"] = "lighten",
                ["datetime"] = "2023-01-24 04:36:02",
                ["chapter"] = "",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().839",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().806",
            },
            [3] = {
                ["text"] = ", who saw the benefit of reissuing this book; to Theodore Cohn",
                ["drawer"] = "lighten",
                ["datetime"] = "2023-01-23 06:30:18",
                ["chapter"] = "",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().424",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().362",
            },
            [1] = {
                ["text"] = "We are grateful to friends and colleagues who read the manuscript and contributed suggestions and criticism.",
                ["drawer"] = "lighten",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().108",
                ["chapter"] = "",
                ["datetime"] = "2023-01-23 06:19:09",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().0",
            },
            [4] = {
                ["text"] = "ALLACE GODDARD",
                ["drawer"] = "lighten",
                ["datetime"] = "2023-01-24 03:45:58",
                ["chapter"] = "",
                ["pos1"] = "/body/DocFragment[5]/body/div/p[4]/span[2]/text().6",
                ["pos0"] = "/body/DocFragment[5]/body/div/p[4]/text()[1].4",
            },
        },
    },
    ["highlights_imported"] = true,
    ["last_xpointer"] = "/body/DocFragment[5]/body/div/h1/strong/text().0",
    ["font_face"] = "Noto Serif",
    ["font_size"] = 22,
    ["copt_view_mode"] = 0,
    ["css"] = "./data/epub.css",
    ["word_spacing"] = {
        [2] = 75,
        [1] = 95,
    },
    ["config_panel_index"] = 1,
    ["copt_block_rendering_mode"] = 3,
    ["copt_embedded_fonts"] = 1,
    ["copt_embedded_css"] = 1,
    ["copt_render_dpi"] = 96,
    ["toc_ticks_ignored_levels"] = {},
    ["word_expansion"] = 0,
    ["copt_b_page_margin"] = 15,
    ["copt_sync_t_b_page_margins"] = 0,
    ["preferred_dictionaries"] = {},
    ["copt_smooth_scaling"] = 0,
    ["copt_nightmode_images"] = 1,
    ["stats"] = {
        ["md5"] = "9ff924f34f97bbf011b6067214538ef5",
        ["highlights"] = 5,
        ["language"] = "en-US",
        ["pages"] = 309,
        ["title"] = "Between Parent and Child",
        ["series"] = "N/A",
        ["notes"] = 2,
        ["authors"] = "Dr. Haim G. Ginott",
    },
    ["copt_status_line"] = 1,
    ["copt_h_page_margins"] = {
        [2] = 10,
        [1] = 10,
    },
    ["copt_t_page_margin"] = 15,
    ["render_dpi"] = 96,
    ["copt_visible_pages"] = 1,
    ["doc_pages"] = 309,
    ["readermenu_tab_index"] = 1,
    ["hyphenation"] = true,
    ["font_family_fonts"] = {},
    ["rotation_mode"] = 0,
    ["visible_pages"] = 1,
    ["disable_fuzzy_search"] = false,
    ["gamma_index"] = 15,
    ["doc_props"] = {
        ["series"] = "",
        ["description"] = "",
        ["language"] = "en-US",
        ["title"] = "Between Parent and Child",
        ["keywords"] = "",
        ["authors"] = "Dr. Haim G. Ginott",
    },
    ["inverse_reading_order"] = false,
    ["page_overlap_style"] = "dim",
    ["cache_file_path"] = "/home/huy/.config/koreader/cache/cr3cache/Between_Pare-ott_38_.epub.9c233b5b.1.cr3",
    ["cjk_width_scaling"] = 100,
    ["partial_md5_checksum"] = "9ff924f34f97bbf011b6067214538ef5",
}
