return {
  ["cache_file_path"] = "/home/huy/.config/koreader/cache/cr3cache/Between_Pare-ott_38_.epub.9c233b5b.1.cr3",
  ["smooth_scaling"] = false,
  ["font_kerning"] = 3,
  ["rotation_mode"] = 0,
  ["copt_visible_pages"] = 1,
  ["readermenu_tab_index"] = 1,
  ["text_lang"] = "en-US",
  ["disable_fuzzy_search"] = false,
  ["config_panel_index"] = 1,
  ["inverse_reading_order"] = false,
  ["copt_b_page_margin"] = 15,
  ["copt_word_spacing"] = {
  95,
  75,
},
  ["copt_word_expansion"] = 0,
  ["copt_view_mode"] = 0,
  ["doc_props"] = {
},
  ["hyph_soft_hyphens_only"] = false,
  ["copt_font_size"] = 22,
  ["show_overlap_enable"] = false,
  ["hyph_force_algorithmic"] = false,
  ["font_base_weight"] = 0,
  ["text_lang_embedded_langs"] = true,
  ["render_dpi"] = 96,
  ["copt_font_base_weight"] = 0,
  ["cjk_width_scaling"] = 100,
  ["toc_ticks_ignored_levels"] = {
},
  ["copt_t_page_margin"] = 15,
  ["embedded_fonts"] = true,
  ["render_mode"] = 0,
  ["hide_nonlinear_flows"] = false,
  ["partial_md5_checksum"] = "9ff924f34f97bbf011b6067214538ef5",
  ["copt_sync_t_b_page_margins"] = 0,
  ["word_spacing"] = {
  95,
  75,
},
  ["visible_pages"] = 1,
  ["last_xpointer"] = "/body/DocFragment[5]/body/div/h1/strong/text().0",
  ["copt_font_gamma"] = 15,
  ["cre_dom_version"] = 20210904,
  ["copt_embedded_css"] = 1,
  ["gamma_index"] = 15,
  ["word_expansion"] = 0,
  ["embedded_css"] = true,
  ["bookmarks_sorted_20220106"] = true,
  ["copt_line_spacing"] = 100,
  ["copt_cjk_width_scaling"] = 100,
  ["font_hinting"] = 2,
  ["header_font_face"] = "Noto Sans",
  ["MORE"] = true,
  ["copt_font_hinting"] = 2,
  ["copt_h_page_margins"] = {
  10,
  10,
},
  ["highlight"] = {
  [5] = {
  [7] = {
},
  [1] = {
},
  [2] = {
},
  [3] = {
},
  [4] = {
},
},
},
  ["EXTRA"] = false,
  ["page_overlap_style"] = "dim",
  ["copt_nightmode_images"] = 1,
  ["bookmarks_sorted"] = true,
  ["nightmode_images"] = true,
  ["doc_pages"] = 142,
  ["percent_finished"] = 0.035211267605634,
  ["stats"] = {
},
  ["copt_render_dpi"] = 96,
  ["highlights_imported"] = true,
  ["font_family_fonts"] = {
},
  ["copt_rotation_mode"] = 0,
  ["floating_punctuation"] = 0,
  ["copt_status_line"] = 1,
  ["bookmarks"] = {
{
  ["pos0"] = "/body/DocFragment[5]/body/div/p[4]/text()[1].4",
  ["highlighted"] = true,
  ["page"] = "/body/DocFragment[5]/body/div/p[4]/text()[1].4",
  ["notes"] = "ALLACE GODDARD",
  ["chapter"] = "",
  ["datetime"] = "2023-01-24 04:35:09",
  ["pos1"] = "/body/DocFragment[5]/body/div/p[4]/span[2]/text().6",
  ["text"] = "from kobo itself",
},
{
  ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().595",
  ["highlighted"] = true,
  ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().595",
  ["notes"] = "Nancy Goddard",
  ["datetime"] = "2023-01-23 06:20:41",
  ["chapter"] = "",
  ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().608",
},
{
  ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().362",
  ["highlighted"] = true,
  ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().362",
  ["notes"] = ", who saw the benefit of reissuing this book; to Theodore Cohn",
  ["datetime"] = "2023-01-23 06:30:18",
  ["chapter"] = "",
  ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().424",
},
{
  ["pos0"] = "/body/DocFragment[5]/body/div/p[1]/text().0",
  ["highlighted"] = true,
  ["page"] = "/body/DocFragment[5]/body/div/p[1]/text().0",
  ["notes"] = "We are grateful to friends and colleagues who read the manuscript and contributed suggestions and criticism.",
  ["datetime"] = "2023-01-23 06:19:09",
  ["chapter"] = "",
  ["pos1"] = "/body/DocFragment[5]/body/div/p[1]/text().108",
},
},
  ["copt_smooth_scaling"] = 0,
  ["highlight_drawer"] = "lighten",
  ["copt_embedded_fonts"] = 1,
  ["copt_block_rendering_mode"] = 3,
  ["preferred_dictionaries"] = {
},
  ["css"] = "./data/epub.css",
  ["hyphenation"] = true,
  ["font_face"] = "Noto Serif",
  ["hyph_trust_soft_hyphens"] = false,
  ["gamma"] = 1,
  ["line_space_percent"] = 100,
  ["copt_font_kerning"] = 3,
  ["font_size"] = 22,
},
